### ISSUE TITLE
The specified 'userID' is not registered

### ISSUE THREAD

**Issue by sekine24106** [futomi/node-omron-hvc-p2#1]
When I used getFaceRecognitionData method setting userID,error message of title was displayed.
But I registered userID in HVC-P2.

```
$ node getFaceRecognitionData.js
Error: The specified `userId` is not registered.
    at Promise (C:\Users\fx24106\myapp\node_modules\node-omron-hvc-p2\lib\HvcP2.
js:889:11)
    at HvcP2.getFaceRecognitionData (C:\Users\fx24106\myapp\node_modules\node-om
ron-hvc-p2\lib\HvcP2.js:879:16)
    at Object.<anonymous> (C:\Users\fx24106\myapp\public\javascripts\getFaceReco
gnitionData.js:7:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
```
```
$ node getFaceRecognitionUsers.js
{
  "userIdList": [
    0,
    1,
    2
  ]
}
```

**Comment by sekine24106** [comment]
I missed. I didn't connect HvcP2 object before use getFaceRecognitionData method.
